services:
  postgres_db:
    image: postgres:15
    container_name: store_keeper_db
    environment:
      POSTGRES_USER: store_keeper_name
      POSTGRES_PASSWORD: store_keeper_password
      POSTGRES_DB: store_keeper_db
    ports:
      - "5432:5432"
#  postgres_test:
#    image: postgres:15
#    container_name: store_keeper_db_test
#    environment:
#      POSTGRES_USER: test_user
#      POSTGRES_PASSWORD: test_password
#      POSTGRES_DB: store_keeper_db_test
#    ports:
#      - "5433:5432"
  app:
    build: .
    container_name: store_keeper_app
    environment:
      APP_CONFIG__DB__URL: postgresql://store_keeper_name:store_keeper_password@postgres_db:5432/store_keeper_db
    depends_on:
      - postgres_db
    ports:
      - "5000:5000"