"""update Product, OrderItem

Revision ID: 06bee468905b
Revises: 29d91596ebed
Create Date: 2024-12-06 22:15:01.319101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bee468905b'
down_revision = '29d91596ebed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_order_items_product_id_products', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_order_items_product_id_products'), 'products', ['product_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_products_category_id_categories', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_products_category_id_categories'), 'categories', ['category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_category_id_categories'), type_='foreignkey')
        batch_op.create_foreign_key('fk_products_category_id_categories', 'categories', ['category_id'], ['id'])
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_items_product_id_products'), type_='foreignkey')
        batch_op.create_foreign_key('fk_order_items_product_id_products', 'products', ['product_id'], ['id'], ondelete='SET DEFAULT')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
