"""update user table2

Revision ID: 2a65f31b5e4a
Revises: ffef4d85fe1c
Create Date: 2024-11-20 18:04:15.456086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a65f31b5e4a'
down_revision = 'ffef4d85fe1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))

    # ### end Alembic commands ###
