"""create supplies table

Revision ID: 6c946dd7b060
Revises: d0860864af65
Create Date: 2024-12-03 16:36:25.183134

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c946dd7b060"
down_revision = "d0860864af65"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.Column("delivery_date", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "delivery", "canceled", name="supply_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplies_supplier_id_suppliers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplies")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supplies")
    # ### end Alembic commands ###
