"""update product table

Revision ID: bba9a468ab6f
Revises: edc5326a5253
Create Date: 2024-11-25 21:12:14.276645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba9a468ab6f'
down_revision = 'edc5326a5253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_products_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_products_name'), type_='unique')

    # ### end Alembic commands ###
