"""create suppliers table

Revision ID: d0860864af65
Revises: bba9a468ab6f
Create Date: 2024-12-03 16:08:22.162288

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d0860864af65"
down_revision = "bba9a468ab6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=50), nullable=True),
        sa.Column("phone_number", sa.VARCHAR(length=20), nullable=True),
        sa.Column("address", sa.VARCHAR(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("name", name=op.f("uq_suppliers_name")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("suppliers")
    # ### end Alembic commands ###
