"""update category table

Revision ID: f1d7a25d74d4
Revises: f4f0cc6e5552
Create Date: 2024-11-19 13:05:55.395252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d7a25d74d4'
down_revision = 'f4f0cc6e5552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorys', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categorys_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categorys_name'), type_='unique')

    # ### end Alembic commands ###
