"""category table

Revision ID: f4f0cc6e5552
Revises: 9b5d0cf8a008
Create Date: 2024-11-18 21:40:30.169826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f0cc6e5552'
down_revision = '9b5d0cf8a008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys',
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorys'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorys')
    # ### end Alembic commands ###
